const reports = [
  {
    workingDate: '2024-05-13',
    reportStatus: '精査済み',
    modificationReason: '',
    commerces: [
      {
        workingDate: '2024-05-13',
        commerceCode: 1001,
        commerceName: '現金売上',
        commerceValueOfReport: 1000,
        commerceValueOfModification: 2000,
      },
      {
        workingDate: '2024-05-13',
        commerceCode: 1002,
        commerceName: 'ギフト券売上',
        commerceValueOfReport: 3000,
        commerceValueOfModification: 3000,
      },
      {
        workingDate: '2024-05-13',
        commerceCode: 1003,
        commerceName: '商品券売上',
        commerceValueOfReport: 5000,
        commerceValueOfModification: 5000,
      },
      {
        workingDate: '2024-05-13',
        commerceCode: 1004,
        commerceName: 'クレジット売上',
        commerceValueOfReport: 30000,
        commerceValueOfModification: 30000,
      },
      {
        workingDate: '2024-05-13',
        commerceCode: 3001,
        commerceName: '現金在高',
        commerceValueOfReport: 8000,
        commerceValueOfModification: 8000,
      },
      {
        workingDate: '2024-05-13',
        commerceCode: 13001,
        commerceName: '客数',
        commerceValueOfReport: 8,
        commerceValueOfModification: 8,
      },
    ],
  },
  {
    workingDate: '2024-05-14',
    reportStatus: '精査済み',
    modificationReason: '現金売上高は入金機と異なるため',
    commerces: [
      {
        workingDate: '2024-05-14',
        commerceCode: 1001,
        commerceName: '現金売上',
        commerceValueOfReport: 1000,
        commerceValueOfModification: 2000,
      },
      {
        workingDate: '2024-05-14',
        commerceCode: 1002,
        commerceName: 'ギフト券売上',
        commerceValueOfReport: 3000,
        commerceValueOfModification: 3000,
      },
      {
        workingDate: '2024-05-14',
        commerceCode: 1003,
        commerceName: '商品券売上',
        commerceValueOfReport: 5000,
        commerceValueOfModification: 5000,
      },
      {
        workingDate: '2024-05-14',
        commerceCode: 1004,
        commerceName: 'クレジット売上',
        commerceValueOfReport: 30000,
        commerceValueOfModification: 30000,
      },
      {
        workingDate: '2024-05-14',
        commerceCode: 3001,
        commerceName: '現金在高',
        commerceValueOfReport: 8000,
        commerceValueOfModification: 8000,
      },
      {
        workingDate: '2024-05-14',
        commerceCode: 13001,
        commerceName: '客数',
        commerceValueOfReport: 8,
        commerceValueOfModification: 8,
      },
    ],
  },
  {
    workingDate: '2024-05-15',
    reportStatus: '報告済み',
    modificationReason: '',
    commerces: [
      {
        workingDate: '2024-05-15',
        commerceCode: 1001,
        commerceName: '現金売上',
        commerceValueOfReport: 1000,
        commerceValueOfModification: 2000,
      },
      {
        workingDate: '2024-05-15',
        commerceCode: 1002,
        commerceName: 'ギフト券売上',
        commerceValueOfReport: 3000,
        commerceValueOfModification: 3000,
      },
      {
        workingDate: '2024-05-15',
        commerceCode: 1003,
        commerceName: '商品券売上',
        commerceValueOfReport: 5000,
        commerceValueOfModification: 5000,
      },
      {
        workingDate: '2024-05-15',
        commerceCode: 1004,
        commerceName: 'クレジット売上',
        commerceValueOfReport: 30000,
        commerceValueOfModification: 30000,
      },
      {
        workingDate: '2024-05-15',
        commerceCode: 3001,
        commerceName: '現金在高',
        commerceValueOfReport: 8000,
        commerceValueOfModification: 8000,
      },
      {
        workingDate: '2024-05-15',
        commerceCode: 13001,
        commerceName: '客数',
        commerceValueOfReport: 8,
        commerceValueOfModification: 8,
      },
    ],
  },
];

export default reports;